# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8d8d5dba824358cf41033aa6f15c064830eb0af6f12c66279919156193a3b00585c4ea94ac49ba5d014213dc3af6e1ae57cee30e4267bcab7ff3016dad77cd56

test:
  secret_key_base: 5a66e1bd568a236458f834fac16adf69c0486ace019c1c30f5ece1f98c777c92dfeaec556627d2eb1ea9a29a261e62ba60f13f53f86984abe32dddcb302c1735

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
